name: whatchord
description: Real-time chord identification via Bluetooth MIDI.

publish_to: none
version: 2026.1.27+3

environment:
  sdk: ^3.10.4
  # pinned version used for automated testing and releases
  flutter: 3.38.6

dependencies:
  flutter:
    sdk: flutter

  auto_size_text: ^3.0.0
  collection: ^1.19.1
  flutter_midi_command: ^0.5.3
  flutter_riverpod: ^3.0.3
  flutter_svg: ^2.2.3
  meta: ^1.17.0
  package_info_plus: ^9.0.0
  permission_handler: ^12.0.1
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2
  wakelock_plus: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/glyphs/keyboard_pedal_ped.svg
    - assets/logo/whatchord_logo_circle.svg

  fonts:
    - family: Bravura
      fonts:
        - asset: assets/fonts/BravuraText.otf
