blank_issues_enabled: true
contact_links:
  - name: Email support (no GitHub account required)
    url: https://github.com/EarthmanMuons/whatchord/blob/main/SUPPORT.md
    about: >
      Instructions for contacting support without a GitHub account.
