blank_issues_enabled: true
contact_links:
  - name: Email support (no GitHub account required)
    url: mailto:support@earthmanmuons.com
    about: >
      If you don't have a GitHub account, or prefer email, you can contact us directly here.
