name: auto-draft release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  draft_release:
    name: draft release
    permissions:
      contents: write
    uses: EarthmanMuons/reusable-workflows/.github/workflows/draft-release-flutter.yml@main
    secrets: inherit
    with:
      slug: whatchord
