name: bump version

on:
  workflow_dispatch:

jobs:
  bump_version:
    name: bump version
    permissions:
      contents: read
    uses: EarthmanMuons/reusable-workflows/.github/workflows/bump-version-flutter-app.yml@main
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
