name: flush caches

on:
  # Allow manually running this workflow.
  workflow_dispatch:

jobs:
  flush_caches:
    name: flush caches
    permissions:
      actions: write
    uses: EarthmanMuons/reusable-workflows/.github/workflows/common/flush-caches.yml@main
